config/routes.rb
Rails.application.routes.draw do

  # like get '/' => 'pages#home'
  root to: 'pages#home'

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create all 7 CRUD routes for our User model
  resources :users

def update
  @user = User.find(params[:id])
  @user.update(user_params)

  redirect_to user_path(@user)

end
  post '/garments/:id/claim' => 'garments#claim', as: 'claim_garment'
  resources :garments
  resources :photos

   post 'photo/store'
   root 'photo#index'
  
#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy





end # routes above here!

app/models/garment.rb
class Garment < ApplicationRecord
  belongs_to :user
  has_many :photos
  attribute :claimed, :boolean, default: false
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController

  before_action :check_if_logged_in

  def claim

    #  1. get the garment by id and the id is in params id.
    garment = Garment.find params[:id]
    # 2. take points off the current user and give them to the owner of the garments.
    garment.user.update points: (garment.user.points + garment.points)
    @current_user.update points: (@current_user.points - garment.points)
    # 3. Garments user id needs to transfer to current user id.
    # 4. Change garment claimed column to true.
    garment.update user_id: @current_user.id, claimed:true

    # 5. current user will be redirected back to profile page and new outfit will now appear.
    redirect_to user_path(@current_user.id)
  end

  def new
    @garment = Garment.new  # make a blank Garment object to give to 'form_with' in the template
  end

  def create

      @garment = Garment.create(
        title:  params[:garment][:title],
        garment_type:  params[:garment][:garment_type],
        points:  params[:garment][:points],
       size:  params[:garment][:size],
       user_id: @current_user.id,
       description: params[:garment][:description]
     )

    if @garment.persisted?
      if params[:file].present?
         # Then call Cloudinary's upload method, passing in the file in params
         response = Cloudinary::Uploader.upload(params[:file])
         # save the response id into the appropriate field of our new model
         # Using the public_id allows us to use Cloudinary's powerful image
         # transformation methods.
         # garment.image = response["public_id"] # this is an URL
         # garment.save
         Photo.create(
           image: response["public_id"],
           garment_id: @garment.id
         )
      end #if file present

      redirect_to garment_path(@garment.id)
    else

      render :new
    end #end of the else if not persisted

   end  #create
  #
   def index
     @garments = Garment.where claimed:false
   end
  #
   def show
     @garment = Garment.find params[:id]
   end
  #
  def garment_params
  params.require(:garment).permit(:title, :body, photos: [])
end
  # def edit
  # end
  #
  # def update
  # end
  #
  def destroy
    Garment.destroy params[:id]
    redirect_to garments_path

  end

   #private

  #def garment_params
     #params.require(:garment).permit(:email, :password, :password_confirmation, :name)
   # end
end # class GarmentsController

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/garments/create.html.erb
<h1>Garments#create</h1>
<p>Find me in app/views/garments/create.html.erb</p>

app/views/garments/destroy.html.erb
<h1>Garments#destroy</h1>
<p>Find me in app/views/garments/destroy.html.erb</p>

app/views/garments/edit.html.erb
<h2>
  Edit garment: <%= @garment.title %>
</h2>

<%= render partial: 'form' %>

app/views/garments/index.html.erb
<h1>Swap Shop </h1>

            <%= token_tag %>

<ul>


<% @garments.each do |garment| %>
  <li>
    <%= link_to garment.title, garment_path(garment.id) %>
  </li>
<% end %>
</ul>

app/views/garments/new.html.erb
<h1>Add garment</h1>

<%= form_with model: @garment, local: true, html: { multipart: true} do |garment| %>

<%= garment.label :title %>
<%= garment.text_field :title %>
<br>
<%= garment.label :garment_type %>
<%= garment.text_field :garment_type %>
<br>
<%= garment.label :description %>
<%= garment.text_area :description %>
<br>
<%= garment.label :size %>
<%= garment.text_field :size %>
<br>
<%= garment.label :points %>
<%= garment.text_field :points %>
<br>
<%= garment.cl_image_upload :image %>
<br><br>
<%= garment.submit %>

<% end %>

app/views/garments/show.html.erb
<h2>
Garments: <%= @garment.title %>
</h2>

<% if @garment.user_id == @current_user.id %>
  <%= link_to 'Edit Garment', edit_garment_path(@garment.id) %>
<% end %>
<p><strong>Points: </strong><%= @garment.points %></p>



<% if @current_user.points >= @garment.points %>
  <%= form_with url:claim_garment_path(@garment.id), local:true do |f| %>
  <%= f.submit "Claim" %>
  <% end %>
<% else %>
<h1>You do not have enough points... yet, swap more clothes!</h1>
<% end %>


  <p>
    <strong>Created by:</strong>
    <%= @garment.user.first_name %>
  </p>

<% @garment.photos.each do |photo|%>
  <%= cl_image_tag(photo.image, alt:photo.caption) %>
<% end %>

app/views/garments/update.html.erb
<h1>Garments#update</h1>
<p>Find me in app/views/garments/update.html.erb</p>