config/routes.rb
Rails.application.routes.draw do

  # like get '/' => 'pages#home'
  root to: 'pages#home'

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create all 7 CRUD routes for our User model
  resources :users

def update
  @user = User.find(params[:id])
  @user.update(user_params)

  redirect_to user_path(@user)

end
  post '/garments/:id/claim' => 'garments#claim', as: 'claim_garment'
  resources :garments
  resources :photos

   post 'photo/store'
   root 'photo#index'
  
#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy





end # routes above here!

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :garment

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :check_if_logged_in, except: [ :index, :show ]

  def new
    @photo = Photo.new # for the 'form_with'
  end

  def create
    # We need to set the .user_id of the photo from @current_user
    # BUT that means the user has to be logged in!
    # So we need to lock down the photo routes, to ensure that
    # only logged-in users can see them

    # Photo.new with strong params creates the object in memory, with
    # the column attributes filled in from the form params... but not saved to DB
    @photo = Photo.new (photo_params)
    @garment.user = @current_user# this photo belongs to the logged-in user
    photo.save  # actually do DB 'INSERT'



    # this photo belongs to the logged-in user

      # Check for file upload and handle upload if present


    # actually do DB 'INSERT'

    # Add the user ID to this photo

    # 1. Set attribute after .create, and then .save
    # photo.user_id = @current_user.id
    # photo.save

    # 2. Use .update instead of setting attribute and .save as separate steps
    # photo.update user_id: @current_user.id

    # 3. Use the '<<' to add to a many association
    # @current_user.photos << photo



    redirect_to photo_path( photo.id ) # go to show page
  end
  def store
          render plain: params[:caption].inspect
        end


  def index
  @posts = Post.all
  end
end

  def show
    @photo = Photo.find params[:id]
  end

  def edit
    @photo = Photo.find params[:id]
    redirect_to login_path unless @photo.user_id == @current_user.id
  end

  def update
    photo = Photo.find params[:id]

    # Don't perform the edit unless the photo belongs to the user
    # redirect_to login_path and return unless photo.user_id == @current_user.id
    if photo.user_id != @current_user.id
      redirect_to login_path
      return
    end #if

    photo.update photo_params # strong params
    redirect_to photo_path(photo.id)
  end #update


  def destroy
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end

end  # class PhotosController

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with model: @photo, local: true, html: { multipart: true} do |photo| %>

<%= photo.label :image %>
<%= photo.text_field :caption %>
<br>
<%= photo.label :image %>
<%= photo.file_field :image %>
<br>
<%= photo.submit %>

<% end %>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h2>
  Edit photos: <%= @photo.caption %>
</h2>

<%= render partial: 'form' %>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<h2>Upload an ensemble</h2>

<%= render partial: 'form' %>

app/views/photos/show.html.erb
<h2>
  Photo: <%= @photo.caption %>
</h2>

<% if @photo.garment.user_id == @current_user.id %>
  <%= link_to 'Edit Photo', edit_photo_path(@photo.id) %>
<% end %>



<%= image_tag @photo.image %>
<h2>
  Photo: <%= @photo.caption%>
</h2>



<%= image_tag @photo.image %>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>