config/routes.rb
Rails.application.routes.draw do

  # like get '/' => 'pages#home'
  root to: 'pages#home'

  # Login/logout routes
  get '/login'  => 'session#new'        # showing the login form
  post '/login' => 'session#create'     # form submits to here, performs login, redirects
  delete '/login' => 'session#destroy'  # logout link goes here, perform logout, redirect

  # Create all 7 CRUD routes for our User model
  resources :users

def update
  @user = User.find(params[:id])
  @user.update(user_params)

  redirect_to user_path(@user)

end
  post '/garments/:id/claim' => 'garments#claim', as: 'claim_garment'
  resources :garments
  resources :photos

   post 'photo/store'
   root 'photo#index'
  
#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy





end # routes above here!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APParel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>



        <header>





        <% if @current_user.present?  %>
          Welcome, <%= @current_user.first_name %>
          |
          <%= link_to 'Logout', login_path, method: 'delete' %>
        <% else %>
          <%= link_to 'Login', login_path %>
          |
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>


<img src="https://res.cloudinary.com/do9y9tnbr/image/upload/v1607571178/APParel_new_ta0eli.png" class="floatRight" alt="company logo" height="300px">

                    <h1>
                Welcome to APParel - the clothes swapping APP</h1>



            </header>

      <hr>

<body>


    <%= yield %>


</body>
    <footer>
      <div class="navfoot">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Login', login_path %>
        <%= link_to '"Buy" Clothes', garments_path %>
        <%= link_to '"Sell" clothes', new_garment_path %>
       <%=  link_to 'User Profile', { id: @current_user } %>



</div>

    </footer>


</html>